### ISSUE TITLE
Add Cake Add to Website

### ISSUE THREAD

**Issue by gep13** [austinlparker/Cake.ISO#1]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by austinlparker** [comment]
Hey, thanks for these issues. I've opened https://github.com/cake-build/website/pull/434 to get this added.

**Comment by gep13** [comment]
@austinlparker I have merged this into the repository.  It should appear on the site the next time we push an update.
