### ISSUE TITLE
Reference Issue

### ISSUE THREAD

**Issue by rdavisunr** [austinlparker/Cake.ISO#4]
I am unable to reference this addin...

There appear to be two issues:

(1) Adding the reference in this way:
#addin "Cake.ISO"

yields this error:
```
Unable to find package 'Cake.ISO'
NuGet exited with 1
An error occured while installing package Cake.ISO.
Error: Failed to install addin 'Cake.ISO'.
```
(2) Adding the reference in this way:
#addin nuget:?package=Cake.ISO&prerelease

yields this error:
```
Error: The assembly 'Cake.ISO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.21.1).
This assembly need to reference at least Cake.Core version 0.22.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

Any guidance would be appreciated...

**Comment by austinlparker** [comment]
I think this is because I neglected to update to support Cake 0.23, pushing an update now that should fix it.

**Comment by austinlparker** [comment]
Ok, can you please try again? Use `#addin "nuget:?package=Cake.ISO&version=0.1.4-alpha"` to specifically target the new version. Let me know how it goes!

**Comment by rdavisunr** [comment]
@austinlparker - thank you very much; all good now!
